apiVersion: apps/v1
kind: Deployment
metadata:
  name: shawty
  namespace: shawty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shawty
  template:
    metadata:
      labels:
        app: shawty
    spec:
      containers:
        - name: shawty
          image: shawty:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: shawty-config
            - secretRef:
                name: shawty-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
